# 1. 定义流水线的三个车间 (Stages)，它们会按顺序执行
stages:
  - setup
  - test
  - report

# 2. 第一个任务：准备环境
install_dependencies:
  stage: setup
  # script 里面写的，就是你想让云端服务器敲的命令行
  script:
    - echo ">>> 开始安装 Python 依赖..."
    - pip install -r requirements.txt

# 3. 第二个任务：跑测试
run_pytest:
  stage: test
  script:
    - echo ">>> 开始执行接口自动化测试..."
    # 和你在本地敲的一模一样，把原始数据塞进 temps 文件夹
    - pytest test_opi_01.py --alluredir=./temps --clean-alluredir
  # artifacts 的作用是“保存证据”：告诉服务器，跑完测试后别把 temps 文件夹删了，后面的车间还要用
  artifacts:
    paths:
      - temps/

# 4. 第三个任务：出报告
generate_allure_report:
  stage: report
  script:
    - echo ">>> 正在把 JSON 数据渲染成 HTML 报告..."
    # 这也是命令行操作，利用之前保留下来的 temps 数据生成最终网页
    - allure generate ./temps -o ./allure-report --clean